"""baseline: schema as of role-based-access + simulator-realism session

Revision ID: 14e1d12725f9
Revises: 
Create Date: 2026-09-11 19:16:25.757274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e1d12725f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Deliberately empty. Every table this baseline covers already exists
    # in the live database -- they were created by Base.metadata.create_all()
    # at app startup, then hand-migrated with direct ALTER TABLE statements
    # for every schema change since (see CLAUDE.md's "Bugs found and fixed"
    # entries 21/23 for two examples of exactly the class of bug that motivated
    # adopting Alembic at all). This revision only marks "Alembic starts
    # tracking from here" via `alembic stamp head` -- it was never `upgrade`d
    # for real. Every migration after this one should contain real
    # operations generated by `alembic revision --autogenerate`.
    pass


def downgrade() -> None:
    pass
